@startuml
'https://plantuml.com/class-diagram

hide empty members

class TP_CharacterController<<M, yellow>>

class ControllerConfiguration<<S, violet>>

class InputConfiguration<<S, violet>>


@enduml