@startuml
'https://plantuml.com/class-diagram

hide empty members

class Sense<<M, yellow>>

interface IPerceptionReceiver<T>
interface IStimulusSource

Sense -> IStimulusSource
Sense --> IPerceptionReceiver


@enduml